
# Site settings
title: Jesse Trippe

# Build settings
include:
  - _pages/
  
collections:
  work_items:
    output: true
    permalink: /work/:name/
    sort_by: order
  invoices:
    output: true
    permalink: /invoices/:name/

exclude:
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - yarn.lock
  - yarn-error.log
  - .jekyll-cache/
