
# Site settings
title: Jesse Trippe
description: "Portfolio of Jesse Trippe - UX/UI Designer who enjoys coding and designing for the web"
url: "https://jesse.desi"
author: "Jesse Trippe"
baseurl: ""

# Build settings
include:
  - _pages/

css_dir: "styles" # defaults to "css"

collections:
  work_items:
    output: true
    permalink: /work/:name/
    sort_by: order
  invoices:
    output: true
    permalink: /invoices/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
